# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userWindow/LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(425, 336)
        LoginWindow.setMinimumSize(QtCore.QSize(425, 336))
        LoginWindow.setMaximumSize(QtCore.QSize(425, 336))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(LoginWindow)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 0, 2, 1, 1)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.gridLayout.addWidget(self.passwordLineEdit, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.btnLogin = QtWidgets.QPushButton(self.groupBox)
        self.btnLogin.setStyleSheet("font: 10pt \"Arial\";")
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout.addWidget(self.btnLogin, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(LoginWindow)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSignup = QtWidgets.QPushButton(self.groupBox_2)
        # self.label_signin = QtWidgets.QLabel(self.groupBox_2)
        self.btnSignup.setObjectName("btnSignup")
        self.horizontalLayout.addWidget(self.btnSignup)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnForgot = QtWidgets.QPushButton(self.groupBox_2)
        # self.label_forgot = QtWidgets.QLabel(self.groupBox_2)
        self.btnForgot.setObjectName("btnForgot")
        self.horizontalLayout.addWidget(self.btnForgot)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(LoginWindow)
        # QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "colorize"))
        self.groupBox.setTitle(_translate("LoginWindow", ""))
        self.label_2.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Password</span></p></body></html>"))
        self.btnLogin.setText(_translate("LoginWindow", "Log in"))
        self.label.setToolTip(_translate("LoginWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Username</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("LoginWindow", ""))
        self.btnSignup.setText(_translate("LoginWindow", "Sign up"))
        self.btnForgot.setText(_translate("LoginWindow", "Forgot password?"))
