# -*- coding: utf-8 -*-

# ChangePasswordWindow implementation generated from reading ui file 'userWindow/signinWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePasswordWindow(object):
    def setupUi(self, ChangePasswordWindow):
        ChangePasswordWindow.setObjectName("ChangePasswordWindow")
        ChangePasswordWindow.resize(400, 200)
        ChangePasswordWindow.setMinimumSize(QtCore.QSize(400, 200))
        ChangePasswordWindow.setMaximumSize(QtCore.QSize(400, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(ChangePasswordWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.oldPasswordLineEdit = QtWidgets.QLineEdit(ChangePasswordWindow)
        self.oldPasswordLineEdit.setObjectName("oldPasswordLineEdit")
        self.gridLayout.addWidget(self.oldPasswordLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ChangePasswordWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(ChangePasswordWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.newPasswordLineEdit = QtWidgets.QLineEdit(ChangePasswordWindow)
        self.newPasswordLineEdit.setObjectName("newPasswordLineEdit")
        self.gridLayout.addWidget(self.newPasswordLineEdit, 2, 1, 1, 1)

        self.confirmLineEdit = QtWidgets.QLineEdit(ChangePasswordWindow)
        self.confirmLineEdit.setObjectName("confirmLineEdit")
        self.gridLayout.addWidget(self.confirmLineEdit, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        # self.passwordLineEdit = QtWidgets.QLineEdit(ChangePasswordWindow)
        # self.passwordLineEdit.setObjectName("passwordLineEdit")
        # self.gridLayout.addWidget(self.passwordLineEdit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ChangePasswordWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnConfirm = QtWidgets.QPushButton(ChangePasswordWindow)
        self.btnConfirm.setStyleSheet("font: 10pt \"Arial\";")
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout.addWidget(self.btnConfirm)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnCancle = QtWidgets.QPushButton(ChangePasswordWindow)
        self.btnCancle.setStyleSheet("font: 10pt \"Arial\";")
        self.btnCancle.setObjectName("btnCancle")
        self.horizontalLayout.addWidget(self.btnCancle)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ChangePasswordWindow)
        # QtCore.QMetaObject.connectSlotsByName(ChangePasswordWindow)

    def retranslateUi(self, ChangePasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangePasswordWindow.setWindowTitle(_translate("ChangePasswordWindow", "Change your password"))
        self.label_2.setText(_translate("ChangePasswordWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">new password</span></p></body></html>"))
        # self.label.setToolTip(_translate("ChangePasswordWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("ChangePasswordWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">old password</span></p></body></html>"))
        self.label_3.setText(_translate("ChangePasswordWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">confirm password</span></p></body></html>"))
        self.btnConfirm.setText(_translate("ChangePasswordWindow", "confirm"))
        self.btnCancle.setText(_translate("ChangePasswordWindow", "cancle"))
