# -*- coding: utf-8 -*-

# SignupWindow implementation generated from reading ui file 'userWindow/signinWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignupWindow(object):
    def setupUi(self, SignupWindow):
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(400, 200)
        SignupWindow.setMinimumSize(QtCore.QSize(400, 200))
        SignupWindow.setMaximumSize(QtCore.QSize(400, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(SignupWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(SignupWindow)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(SignupWindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(SignupWindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.passwordLineEdit = QtWidgets.QLineEdit(SignupWindow)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 2, 1, 1, 1)

        self.confirmLineEdit = QtWidgets.QLineEdit(SignupWindow)
        self.confirmLineEdit.setObjectName("confirmLineEdit")
        self.gridLayout.addWidget(self.confirmLineEdit, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        # self.passwordLineEdit = QtWidgets.QLineEdit(SignupWindow)
        # self.passwordLineEdit.setObjectName("passwordLineEdit")
        # self.gridLayout.addWidget(self.passwordLineEdit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(SignupWindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSignup = QtWidgets.QPushButton(SignupWindow)
        self.btnSignup.setStyleSheet("font: 10pt \"Arial\";")
        self.btnSignup.setObjectName("btnSignup")
        self.horizontalLayout.addWidget(self.btnSignup)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnCancle = QtWidgets.QPushButton(SignupWindow)
        self.btnCancle.setStyleSheet("font: 10pt \"Arial\";")
        self.btnCancle.setObjectName("btnCancle")
        self.horizontalLayout.addWidget(self.btnCancle)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SignupWindow)
        # QtCore.QMetaObject.connectSlotsByName(SignupWindow)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "Signup"))
        self.label_2.setText(_translate("SignupWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Password</span></p></body></html>"))
        # self.label.setToolTip(_translate("SignupWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("SignupWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Username</span></p></body></html>"))
        self.label_3.setText(_translate("SignupWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Confirm password</span></p></body></html>"))
        self.btnSignup.setText(_translate("SignupWindow", "Sign up"))
        self.btnCancle.setText(_translate("SignupWindow", "Cancle"))
